---
- hosts: all
  vars:
    - config: "{{ playbook_dir }}/oneview_config.json"
    - datacenter_new_name: "Datacenter XYZ"
  tasks:
    - name: Gather facts about all Data Centers
      oneview_datacenter_facts:
        config: "{{ config }}"
      delegate_to: localhost

    - debug: var=datacenters

    - name: Rename the Data Center
      oneview_datacenter:
        config: "{{ config }}"
        state: present
        data:
            name: "{{ datacenters[0].name }}"
            newName: "{{ datacenter_new_name }}"
      delegate_to: localhost
