- hosts: all
  vars:
    - config: "{{ playbook_dir }}/oneview_config.json"
  vars_files:
    - "{{ playbook_dir }}/vars/enclosures.yml"

  tasks:
    - name: Print enclosures records
      debug: msg="Enclosure {{ item.key }}"
      with_dict: "{{ enclosures }}"

    - name: Update the name of the enclosures
      oneview_enclosure:
        config: "{{ config }}"
        state: present
        data:
          name: "{{ item.key }}"
          newName: "{{ item.value.newname }}"
      with_dict: "{{ enclosures }}"
      delegate_to: localhost

