- hosts: all
  vars:
    - config: "{{ playbook_dir }}/oneview_config.json"
  vars_files:
    - "{{ playbook_dir }}/vars/sas_lig.yml"
  tasks:
    - name: Create a SAS Logical Interconnect Group
      oneview_sas_logical_interconnect_group:
        config: "{{ config }}"
        state: present
        data:
            name: '{{ item.value.name }}'
            type: '{{ item.value.type }}'
            enclosureType: '{{ item.value.enclosureType }}'
            enclosureIndexes: '{{ item.value.enclosureIndexes }}'
            interconnectBaySet: '{{ item.value.interconnectBaySet }}'
            interconnectMapTemplate: '{{ item.value.interconnectMapTemplate }}'
      with_dict: "{{ sas_logical_interconnect_group }}"
      delegate_to: localhost
