---
- hosts: all
  vars:
    - config: "{{ playbook_dir }}/oneview_config.json"
  tasks:
    - name: Gather facts about all Enclosures
      oneview_enclosure_facts:
        config: "{{ config }}"
      delegate_to: localhost


    - set_fact:
        enc: "{{enclosures | map(attribute='uri') | list}}"
    - debug: var=enc
