---
- hosts: localhost
  vars:
    - config: "{{ playbook_dir }}/oneview_config.json"
  tasks:
    - name: Gather facts about all Interconnect Types and filter for FC interconnect
      oneview_interconnect_type_facts:
        config: "{{ config }}"
      delegate_to: localhost


    - debug: msg="{{interconnect_types | map(attribute='name') | list }}"

    - debug: msg="{% for result in interconnect_types %}
                  {% if 'FC' in result.name %}
                       {{ result.name }}
                       {{ result.uri }}
                  {% endif %}
                  {% endfor %}"
      register: ic_fc


    - debug: msg="{% for result in interconnect_types %}
                  {% if ( 'Virtual Connect SE 40Gb' in result.name ) or ( 'Interconnect Link Module' in result.name ) %}
                       {{ result.name }}
                       {{ result.uri }}
                  {% endif %}
                  {% endfor %}"
      register: ic_vc

