---
- hosts: all
  vars:
    - config: "{{ playbook_dir }}/oneview_config.json"
  tasks:
    - name: Gather facts about all Ethernet Networks
      oneview_ethernet_network_facts:
        config: "{{ config }}"
      delegate_to: localhost


    - debug: msg="{% for result in ethernet_networks %}
                     {{ result.name }}
                     {{ result.uri }}
                  {% endfor %}"
      register: ether

    - debug: var=ether
