---
- hosts: all
  vars:
    - config: "{{ playbook_dir }}/oneview_config.json"
  tasks:
    - name: Gather facts about all Storage Pools
      oneview_storage_pool_facts:
        config: "{{ config }}"
      delegate_to: localhost




    - debug: msg="{% for result in storage_pools %} 
                    {{ result.name }}, {{ result.storageSystemUri }}, {{ result.uri }} 
                  {% endfor %}"

