---
- hosts: all
  vars:
    - config: "{{ playbook_dir }}/oneview_config.json"
  tasks:
    - name: Gather facts about all Logical Interconnect Groups
      oneview_logical_interconnect_group_facts:
        config: "{{ config }}"
      delegate_to: localhost
    - debug: var=logical_interconnect_groups

    - name: Gather facts about all SAS Logical Interconnect Groups
      oneview_sas_logical_interconnect_group_facts:
        config: "{{ config }}"
      delegate_to: localhost

    - debug: var=sas_logical_interconnect_groups
