---
- hosts: all
  vars:
    - config: "{{ playbook_dir }}/oneview_config.json"
  tasks:
    - name: Gather facts about the last 2 tasks
      oneview_task_facts:
        config: "{{ config }}"
        params:
          count: 2

